"""Atomic JSON storage for a single backend process."""
import json
import logging
import os
from pathlib import Path
from uuid import UUID, uuid4


class RunStore:
    def __init__(self, directory):
        self.directory = Path(directory)
        self.directory.mkdir(parents=True, exist_ok=True)

    def save(self, run_id, record):
        # IDs are generated by the server; never allow arbitrary file paths.
        if str(UUID(run_id)) != run_id:
            raise ValueError("Invalid run ID")
        target = self.directory / f"{run_id}.json"
        temporary = self.directory / f"{run_id}.{uuid4()}.tmp"
        try:
            with temporary.open('w', encoding='utf-8') as output:
                json.dump(record, output, ensure_ascii=False, allow_nan=False)
                output.flush()
                os.fsync(output.fileno())
            os.replace(temporary, target)
        finally:
            temporary.unlink(missing_ok=True)

    def load(self):
        records = {}
        for path in self.directory.glob('*.json'):
            try:
                if str(UUID(path.stem)) != path.stem:
                    continue
                record = json.loads(path.read_text(encoding='utf-8'))
                if not isinstance(record, dict) or record.get('status') not in {
                    'queued', 'running', 'completed', 'failed'
                } or 'result' not in record or 'error' not in record:
                    raise ValueError('Invalid saved record')
                if record['status'] == 'completed' and not isinstance(record['result'], dict):
                    raise ValueError('Missing completed result')
            except (ValueError, OSError):
                logging.exception('Cannot load saved run %s', path.name)
                continue
            if record['status'] in {'queued', 'running'}:
                record.update(status='failed', result=None,
                              error='Сервер перезапущен до завершения расчёта. Создайте новый запуск.')
                self.save(path.stem, record)
            records[path.stem] = record
        return records
